apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://helm.cilium.io/
    chart: cilium
    targetRevision: "1.18.0"
    helm:
      values: |
        kubeProxyReplacement: "disabled"
        routingMode: "tunnel"
        tunnel: "vxlan"

        enableXDP: false
        xdp:
          enabled: false
        bpf:
          enabled: false

        ipv4:
          enabled: true
        ipv6:
          enabled: false

        ipam:
          mode: cluster-pool
          operator:
            clusterPoolIPv4PodCIDRList:
              - "10.42.0.0/16"
            clusterPoolIPv4MaskSize: 24

        enableIPv4Masquerade: true

        operator:
          replicas: 1

        hubble:
          enabled: true
          metrics:
            enableOpenMetrics: true
            enabled:
              - dns
              - drop
              - tcp
              - flow
              - port-distribution
              - icmp
              - http
          relay:
            enabled: true
          ui:
            enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
