apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://helm.cilium.io/
    chart: cilium
    targetRevision: 1.15.5
    helm:
      releaseName: cilium
      values: |
        # Replace kube-proxy entirely
        kubeProxyReplacement: strict

        # Your master node API endpoint
        k8sServiceHost: 10.0.1.1
        k8sServicePort: 6443

        # Networking mode (same as your running config)
        routingMode: tunnel
        tunnelProtocol: vxlan

        # IPAM is Kubernetes (matches your cluster)
        ipam:
          mode: kubernetes

        # Disable Hubble (you don't want it)
        hubble:
          enabled: false

        # Disable ClusterMesh
        clustermesh:
          enabled: false

        # CNI replacement (Cilium manages networking)
        cni:
          exclusive: true

        # Basic IPv4 config (same as your cluster)
        ipv4:
          enabled: true
        ipv6:
          enabled: false

        # Enable L7 proxy (default, used by Cilium)
        enableL7Proxy: true

        # Masquerading (NAT) enabled
        enableIPv4Masquerade: true

        # Operator configuration
        operator:
          replicas: 1

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true

