apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://helm.cilium.io/
    chart: cilium
    targetRevision: 1.15.5
    helm:
      releaseName: cilium
      values: |
        kubeProxyReplacement: "strict"
        routingMode: "native"

        ipam:
          mode: "kubernetes"

        cni:
          exclusive: true
        writeCniConfWhenReady: "/host/etc/cni/net.d/05-cilium.conflist"

        enableIPv4: true
        enableIPv6: false

        # FIXED: Hardcoded correct internal API server IP
        k8sServiceHost: "10.0.1.1"
        k8sServicePort: 6443

        enableL7Proxy: true
        enableIPv4Masquerade: true
        enableSvcSourceRangeCheck: true

        hubble:
          enabled: true
          listenAddress: ":4244"
          tls:
            serverSecret: "hubble-server-certs"

        clustermesh:
          enabled: false

        operator:
          replicas: 1

        enableMetrics: true
        operatorPrometheusServeAddr: ":9963"

        enableK8sNetworkPolicy: true
        enableEndpointHealthChecking: true
        enableHealthChecking: true
        removeCiliumNodeTaints: true
        setCiliumNodeTaints: true
        setCiliumIsUpCondition: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
