{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-servicemonitor
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  endpoints:
    - port: https
      interval: {{ .Values.serviceMonitor.interval }}
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
{{- end }}
