apiVersion: v1
kind: Service
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  selector:
    app.kubernetes.io/name: argocd-repo-server
  type: ClusterIP
